name: Docker Publish
on:
  workflow_dispatch:    
jobs:
  DockerPublish:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: publish        
        run: |
          docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
          docker build -t ghcr.io/"${{ github.actor }}"/animeflix:latest .              
          docker push ghcr.io/"${{ github.actor }}"/animeflix:latest
